[package]
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
keywords = ["biology", "scientific", "uniprot", "database"]
license = "MIT"
name = "bdb"
readme = "README.md"
version = "0.1.0"

[dependencies]
assert_approx_eq = "1"
csv = "1"
digit_group = "0.1"
lazy_static = "1"
regex = "1"
reqwest = "0.9.2"
static_assertions = "0.2.5"
url = "1"

[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
